### ISSUE TITLE
Markdown的页面标题显示应该有点问题

### ISSUE THREAD

**Issue by dongxiem** [hshanx/halo-theme-hshan#23]
![image](https://user-images.githubusercontent.com/22069333/75431569-f8ed9c00-5987-11ea-8dcd-64e2c9cdff65.png)

如上所示，标题的前面都会插入一个'#'符号，建议可以检查一下。

**Comment by ghost** [comment]
这个是皮肤的，兄弟

**Comment by dongxiem** [comment]
> 这个是皮肤的，兄弟

这不是页面标题出现问题了？按道理#应该是隐藏的吧？

**Comment by ghost** [comment]
> > 这个是皮肤的，兄弟
> 
> 这不是页面标题出现问题了？按道理#应该是隐藏的吧？

所有的标题都有这个标记的，就是皮肤

**Comment by xzhuz** [comment]
> > 这个是皮肤的，兄弟
> 
> 这不是页面标题出现问题了？按道理#应该是隐藏的吧？

代码有一个样式：
```css
.post-content>h1:before,
.post-content>h2:before,
.post-content>h3:before,
.post-content>h4:before,
.post-content>h5:before,
.post-content>h6:before {
  content: "# ";
  color: var(--base-color);
}
```
