### ISSUE TITLE
希望大佬能够添加首部图片的滤镜功能

### ISSUE THREAD

**Issue by luvying** [hshanx/halo-theme-hshan#58]
很喜欢大佬这套主题，希望大佬能够添加首部图片的滤镜功能，类似于[Siren](https://github.com/halo-dev/halo-theme-siren)那套主题，可以选择浅色、暗淡、网格三种滤镜（举个栗子哈），作用于全部首部图片就好了~ 目前主题都是暗色而且没法调，奈何本人技术渣改不动。。。或者大佬觉得麻烦的话，开放首部图片的CSS自定义代码也好~

**Comment by xzhuz** [comment]
这个还真没有研究过，可以研究研究

**Comment by zyk1994** [comment]
> 很喜欢大佬这套主题，希望大佬能够添加首部图片的滤镜功能，类似于[Siren](https://github.com/halo-dev/halo-theme-siren)那套主题，可以选择浅色、暗淡、网格三种滤镜（举个栗子哈），作用于全部首部图片就好了~ 目前主题都是暗色而且没法调，奈何本人技术渣改不动。。。或者大佬觉得麻烦的话，开放首部图片的CSS自定义代码也好~

别的没有看,首页图片的在main.css 里面有个.cover-bg把opacity调高就不暗了

**Comment by luvying** [comment]
拼凑出来了~在main.min.css 添加/修改下面内容，就可以如siren主题那样给首页图片加“滤镜”，试了下和暗夜模式不冲突
```CSS
/*
  cxy add .cover-bg::before
  edit opacity: .3; --> opacity: .7;(@keyframes fadein) 
  edit opacity: .3; --> opacity: .7;(cover-bg) 
  修改亮度的话两个opacity需要同时修改,否则刚进入网页的时候背景会跳亮
*/
.cover-bg::before {
	content: '';
	position: absolute;
	top: 0;
	bottom: 0;
	left: 0;
	right: 0;
	z-index: 3;
	background-attachment: fixed;
	background-image: url(https://cdn.jsdelivr.net/gh/cxying/ying-blog-cdn@1.0.7/files/static/images/grid.png);
}
```
background-image是我自己的给它加上条纹的效果（类似于Siren那套主题）
